/**
 * Run: ~/.deno/bin/deno test src/lib/bike-ftp-estimator.test.ts --no-check
 *
 * Curves with a KNOWN answer, plus every abstain path: too few durations, absurd W', points that do not
 * describe one curve. Power only (2026-09-04). docs/SPEC-ftp-estimator-2026-09-04.md.
 */
import { assert, assertEquals } from 'https://deno.land/std@0.224.0/assert/mod.ts';
import {
  bestPerDuration,
  fitCriticalPower,
  compoundFtp,
  POWER_CURVE_DURATIONS,
  type SignalBResult,
} from './bike-ftp-estimator.ts';

// ─── a curve generated by the model, so the fit has a known answer ────────
const CP = 250, WP = 20000;
const pAt = (s: number) => CP + WP / s;

Deno.test('POWER_CURVE_DURATIONS — the twelve stored labels, 20min and 60min unchanged', () => {
  assertEquals(POWER_CURVE_DURATIONS.map((d) => d.label), ['5s', '1min', '2min', '3min', '5min', '8min', '10min', '12min', '20min', '30min', '45min', '60min']);
  assertEquals(POWER_CURVE_DURATIONS.find((d) => d.label === '20min')!.seconds, 1200);
});

Deno.test('bestPerDuration — takes the best at each duration across rides, ignores _hr', () => {
  const pts = bestPerDuration([
    { '5min': 280, '20min': 240, _hr: { '20min': 160 } },
    { '5min': 300, '2min': 350 },
    null,
  ]);
  assertEquals(pts, [{ seconds: 120, watts: 350 }, { seconds: 300, watts: 300 }, { seconds: 1200, watts: 240 }]);
});

Deno.test('Signal B — recovers CP and W\' from a curve generated by the model, FTP = 0.97 × CP', () => {
  const pts = [120, 180, 300, 600, 1200, 1800].map((s) => ({ seconds: s, watts: pAt(s) }));
  const b = fitCriticalPower(pts);
  assert(b.value != null, b.reason);
  assertEquals(b.n, 5); // 30 min sits outside the model's domain
  assert(Math.abs((b.cp ?? 0) - CP) <= 1, `cp ${b.cp}`);
  assert(Math.abs((b.wPrime ?? 0) - WP) <= 400, `W' ${b.wPrime}`);
  assert(Math.abs((b.value ?? 0) - CP * 0.97) <= 1, `ftp ${b.value}`);
  assertEquals(b.confidence, 'high');
});

Deno.test('Signal B — a curve that bends below the model past 20 min still fits on 2-20 (the first back-run\'s athlete)', () => {
  const pts = [[2, 256], [3, 229], [5, 210], [8, 193], [10, 191], [12, 186], [20, 177], [30, 158], [45, 150], [60, 132]]
    .map(([m, w]) => ({ seconds: m * 60, watts: w }));
  const b = fitCriticalPower(pts);
  assert(b.value != null, b.reason);
  assertEquals(b.n, 7);
  assert((b.r2 ?? 0) >= 0.99, `r² ${b.r2}`);
  assert(Math.abs((b.cp ?? 0) - 172) <= 1, `cp ${b.cp}`);
  assertEquals(b.value, 167);
});

Deno.test('Signal B — sprint durations are excluded from the fit', () => {
  const pts = [5, 60, 120, 300, 1200].map((s) => ({ seconds: s, watts: s <= 60 ? 900 : pAt(s) }));
  const b = fitCriticalPower(pts);
  assertEquals(b.n, 3);
  assert(Math.abs((b.cp ?? 0) - CP) <= 1, `cp ${b.cp}`);
  assertEquals(b.confidence, 'medium');
});

Deno.test('Signal B — abstains on fewer than 3 aerobic-band durations', () => {
  const b = fitCriticalPower([{ seconds: 300, watts: 300 }, { seconds: 1200, watts: 260 }]);
  assertEquals(b.value, null);
  assert(/need 3/.test(b.reason), b.reason);
});

Deno.test('Signal B — abstains on a physiologically absurd W\'', () => {
  const pts = [120, 300, 600, 1200].map((s) => ({ seconds: s, watts: Math.round(200 + 90_000 / s) }));
  const b = fitCriticalPower(pts);
  assertEquals(b.value, null);
  assert(/implausible W'/.test(b.reason), b.reason);
});

Deno.test('Signal B — abstains when the points do not describe one curve', () => {
  const b = fitCriticalPower([
    { seconds: 120, watts: 320 }, { seconds: 300, watts: 240 }, { seconds: 600, watts: 300 }, { seconds: 1200, watts: 230 },
  ]);
  assertEquals(b.value, null);
  assert(/r²|does not fall/.test(b.reason), b.reason);
});

// ─── combining ───────────────────────────────────────────────────────────

const sigB = (value: number | null, confidence: SignalBResult['confidence'], n = 4): SignalBResult => ({ value, confidence, n, reason: 'b', cp: value, wPrime: 20000, r2: 0.97, points: [] });

Deno.test('compound — the power-duration fit is the estimate, confidence carried through', () => {
  const c = compoundFtp(sigB(200, 'medium'))!;
  assertEquals(c.value, 200);
  assertEquals(c.confidence, 'medium');
  assert(/power-duration fit/.test(c.source));
});

Deno.test('compound — the fit abstains ⇒ null, never a fabricated number', () => {
  assertEquals(compoundFtp(sigB(null, null, 1)), null);
});

