[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# SPA routing fallback (also covered by public/_redirects)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
