[functions]
verify_jwt = false

[functions.headers]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Headers = "authorization, x-client-info, apikey, content-type"
Access-Control-Allow-Methods = "POST, OPTIONS"

